[build]
  command = "pnpm run build"
  publish = ".netlify/functions/server"
  functions = ".netlify/functions"
  base = "app"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS =

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"