[build]
  command = "pnpm run build"
  publish = ".netlify/functions/server"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"