import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'themeSettings',
  title: 'Theme Settings',
  type: 'document',
  fields: [
    defineField({
      name: 'colors',
      title: 'Colors',
      type: 'object',
      fields: [
        {
          name: 'red',
          title: 'Red Colors',
          type: 'object',
          fields: [
            { name: '50', title: '50', type: 'string', initialValue: '#FFF1F1' },
            { name: '100', title: '100', type: 'string', initialValue: '#FFDFDF' },
            { name: '200', title: '200', type: 'string', initialValue: '#FFC5C5' },
            { name: '300', title: '300', type: 'string', initialValue: '#FF9D9D' },
            { name: '400', title: '400', type: 'string', initialValue: '#FF6464' },
            { name: '500', title: '500', type: 'string', initialValue: '#FF1E1E' },
            { name: '600', title: '600', type: 'string', initialValue: '#ED1515' },
            { name: '700', title: '700', type: 'string', initialValue: '#C80D0D' },
            { name: '800', title: '800', type: 'string', initialValue: '#A50F0F' },
            { name: '900', title: '900', type: 'string', initialValue: '#881414' },
          ],
        },
        {
          name: 'green',
          title: 'Green Colors',
          type: 'object',
          fields: [
            { name: '50', title: '50', type: 'string', initialValue: '#FDFFE4' },
            { name: '100', title: '100', type: 'string', initialValue: '#F9FFC4' },
            { name: '200', title: '200', type: 'string', initialValue: '#F1FF90' },
            { name: '300', title: '300', type: 'string', initialValue: '#E2FF50' },
            { name: '400', title: '400', type: 'string', initialValue: '#CCFF00' },
            { name: '500', title: '500', type: 'string', initialValue: '#B2E600' },
            { name: '600', title: '600', type: 'string', initialValue: '#8AB800' },
            { name: '700', title: '700', type: 'string', initialValue: '#688B00' },
            { name: '800', title: '800', type: 'string', initialValue: '#526D07' },
            { name: '900', title: '900', type: 'string', initialValue: '#455C0B' },
          ],
        },
        {
          name: 'gray',
          title: 'Gray Colors',
          type: 'object',
          fields: [
            { name: '50', title: '50', type: 'string', initialValue: '#F6F6F6' },
            { name: '100', title: '100', type: 'string', initialValue: '#E7E7E7' },
            { name: '200', title: '200', type: 'string', initialValue: '#D1D1D1' },
            { name: '300', title: '300', type: 'string', initialValue: '#B0B0B0' },
            { name: '400', title: '400', type: 'string', initialValue: '#888888' },
            { name: '500', title: '500', type: 'string', initialValue: '#6D6D6D' },
            { name: '600', title: '600', type: 'string', initialValue: '#5D5D5D' },
            { name: '700', title: '700', type: 'string', initialValue: '#4C4C4C' },
            { name: '800', title: '800', type: 'string', initialValue: '#454545' },
            { name: '900', title: '900', type: 'string', initialValue: '#3D3D3D' },
          ],
        },
        {
          name: 'blueGray',
          title: 'Blue Gray Colors',
          type: 'object',
          fields: [
            { name: '50', title: '50', type: 'string', initialValue: '#F4F6F7' },
            { name: '100', title: '100', type: 'string', initialValue: '#E4E7E9' },
            { name: '200', title: '200', type: 'string', initialValue: '#CBD1D6' },
            { name: '300', title: '300', type: 'string', initialValue: '#A7B0B9' },
            { name: '400', title: '400', type: 'string', initialValue: '#7B8795' },
            { name: '500', title: '500', type: 'string', initialValue: '#606C7A' },
            { name: '600', title: '600', type: 'string', initialValue: '#535B67' },
            { name: '700', title: '700', type: 'string', initialValue: '#474E57' },
            { name: '800', title: '800', type: 'string', initialValue: '#3F434B' },
            { name: '900', title: '900', type: 'string', initialValue: '#383C41' },
          ],
        },
        {
          name: 'tourquis',
          title: 'Tourquis Colors',
          type: 'object',
          fields: [
            { name: '500', title: '500', type: 'string', initialValue: '#33cc99' },
          ],
        },
      ],
    }),
    defineField({
      name: 'screens',
      title: 'Screen Breakpoints',
      type: 'object',
      fields: [
        { name: 'sm', title: 'Small', type: 'string', initialValue: '640px' },
        { name: 'md', title: 'Medium', type: 'string', initialValue: '768px' },
        { name: 'lg', title: 'Large', type: 'string', initialValue: '1024px' },
        { name: 'xl', title: 'Extra Large', type: 'string', initialValue: '1280px' },
        { name: '2xl', title: '2X Large', type: 'string', initialValue: '1536px' },
      ],
    }),
  ],
})
